REST.connection.Connection Type=${{REST_CONNECTION_TYPE}}
REST.connection.TLS Version=
REST.connection.Connection URL=${{REST_URL}}
REST.connection.Enable two way SSL for outbound connections (Optional)=
REST.connection.Identity keystore alias name (Optional)=
REST.agentDefinition=${{REST_AGENT_DEFINITION}}
